version: "3"
services:
<<<<<<< HEAD
  exercise3:
    build: .
    ports:
     - "9003:9003"
=======
  exercise4:
    build: .
    ports:
     - "9004:9004"
>>>>>>> 72ef50ce623791d52e755763de8db21719439fb0
  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
